### ISSUE TITLE
MCLOUD-5797: Compose build is failing if Blackfire configuration present

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#146]
[MCLOUD-5797](https://jira.corp.magento.com/browse/MCLOUD-5797):
### Preconditions

1. Cloud project is cloned locally

### Steps to reproduce

1. Have the next config in `.magento.app.yaml`:
```
runtime:
    extensions:
        - mcrypt
        - redis
        - xsl
        - json
        - blackfire
        - newrelic
        -
            name: "blackfire"
            configuration:
                server_id: ""
                server_token: ""
```
2. Run `build:compose`

### Expected result

1. Docker build is successful

### Actual result

1. Docker build fails with `array to string conversion

![teminal screenshot](https://user-images.githubusercontent.com/3396658/73947729-94c24580-48bd-11ea-82fe-9471c5616d7f.png)
