### ISSUE TITLE
Introduce universal configuration file

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#160]
To be able to support platform-agnostic Cloud Docker, we must add a universal file that can be included on the project level and be a source for building compose configuration.

# File structure

## General structure

```yaml
services: [] # List of services
variables: [] # List of environment variables
hooks: [] # List of available hooks
mounts: [] #l List of available mounts
```

### Services

Consists of `version`, and `enabled` fields:

```yaml
services:
  php:
    version: "7.2"
    enabled: true|false
```

* If `enabled` property is not set, it will be set to `true` by default.
* Available services: `php`, `mysql`, `redis` etc.

#### PHP service

This service has additional properties: `extensions.enabled` and `extensions.disabled`

```yaml
services:
  php:
    version: "7.2"
    extensions:
      enabled:
        - xsl
      disabled:
        - opcache
```

- If `extensions.enabled` is not provided, PHP will be run with default extensions.

#### Cron service

To enable cron, add `cron` service:

```yaml
services:
  cron:
    jobs:
      run:
        schedule: "* * * * *"
        command: "php bin/magento cron:run"
```

### Hooks

Hooks section consist of `name: commands` list

```yaml
hooks:
  build: |
    set -e
    php ./vendor/bin/ece-tools run scenario/build/generate.xml
    php ./vendor/bin/ece-tools run scenario/build/transfer.xml
  deploy: |
    php ./vendor/bin/ece-tools run scenario/deploy.xml
  post_deploy: |
    php ./vendor/bin/ece-tools run scenario/post-deploy.xml
```

### Variables

Variables may be passed into the environment in the following format:

```yaml
variables:
  DUMMY_VARIABLE: "some value"
  DUMMY_ARRAY_VARIABLE:
    TEST_VALUE: "value"
    TEST_VALUE2: 2
```

* Array variables will be encoded with `base64+json_encode`

### Mounts

Mounts section consists of `name: parameters` named mounts:

```yaml
# .magento.docker.yaml
mounts:
  var:
    path: "var"
  app-etc:
    path: "app/etc"
  pub-media:
    path: "pub/media"
  pub-static:
    path: "pub/static
```

- `path` is a required parameter to define a mounted volume
- `path` is a relative path in the container

**Comment by shiftedreality** [comment]
Internal task: https://magento2.atlassian.net/browse/MAGECLOUD-5421

**Comment by YPyltiai** [comment]
@shiftedreality , wouldn't it be better to do PHP extensions with additional layer like:

```
# .magento.docker.yaml
services:
  php:
    version: "7.2"
    extensions:
      enabled:
        - xsl
      disabled:
        - opcache
```
This grouping looks more logical for me personally.
