### ISSUE TITLE
Docker compose fails if multiple users for mysql configured

### ISSUE THREAD

**Issue by munkhulzii** [magento/magento-cloud-docker#169]
### Preconditions

1. New cloud project installed locally

### Steps to reproduce

1. Multiple mysql user added in services.yml, as described here https://devdocs.magento.com/cloud/project/project-conf-files_services-mysql.html
```
mysql:
    type: mysql:10.2
    disk: 2048
    configuration:
        schemas:
            - main
        endpoints:
            admin:
                default_schema: main
                privileges:
                    main: admin
            reporter:
                privileges:
                    main: ro

redis:
    type: redis:5.0

elasticsearch:
    type: elasticsearch:6.5
    disk: 1024
```

2. Run `./vendor/bin/ece-docker build:compose --mode="developer"` 
 

### Expected result

1. Docker build is successful

### Actual result

1. It fails with error: 

```
In Config.php line 96:                                                  
  Only one instance of service "mysql" supported  
                                                  
In Reader.php line 90:
  Only one instance of service "mysql" supported 
```
