### ISSUE TITLE
Integration Tests will not run completely as "ps" is missing

### ISSUE THREAD

**Issue by azngeek** [magento/magento-cloud-docker#20]
The package procps is missing, so you will not have "ps" available as command. I don't know if anybody uses this for integration tests.

**Comment by shiftedreality** [comment]
Hello, thank you for your request.

Created task MAGECLOUD-3278 to add this.

**Comment by oshmyheliuk** [comment]
Looks like `procps` package is installed by default

```
exec -it magecloud-cron_1 bash
root@cron:/var/www/magento# apt-get install procps
Reading package lists... Done
Building dependency tree
Reading state information... Done
procps is already the newest version (2:3.3.12-3+deb9u1).
procps set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
```
And ps command works as well.

@azngeek Do you actually have a problem with running `ps` command or it's just an assumption?

**Comment by azngeek** [comment]
@oshmyheliuk Which Dockerfile are you using? Can you post the actual configuration?

**Comment by oshmyheliuk** [comment]
https://github.com/magento/magento-cloud-docker/blob/master/php/7.2-cli/Dockerfile
https://github.com/magento/magento-cloud-docker/blob/master/php/7.2-fpm/Dockerfile


From docker-compose file:
```
  ....
  fpm:
    image: 'magento/magento-cloud-docker-php:7.2-fpm'
    ports:
      - 9000
    depends_on:
      - db
    volumes_from:
      - appdata
    volumes:
      - '.:/var/www/magento:ro'
    env_file:
      - ./docker/global.env
      - ./docker/config.env
  build:
    image: 'magento/magento-cloud-docker-php:7.2-cli'
    hostname: build.magento2.docker
    depends_on:
      - db
      - redis
    volumes:
      - '~/.composer/cache:/root/.composer/cache'
      - '.:/var/www/magento:rw'
    volumes_from:
      - appdata
    env_file:
      - ./docker/global.env
      - ./docker/config.env
  deploy:
    image: 'magento/magento-cloud-docker-php:7.2-cli'
    hostname: deploy.magento2.docker
    depends_on:
      - db
      - redis
    volumes:
      - '~/.composer/cache:/root/.composer/cache'
      - '.:/var/www/magento:ro'
    volumes_from:
      - appdata
    env_file:
      - ./docker/global.env
      - ./docker/config.env
 ....
```
