### ISSUE TITLE
Expose all services at well-known ports

### ISSUE THREAD

**Issue by joeshelton-wagento** [magento/magento-cloud-docker#217]
Currently, the web entrypoints are mapped to well-known ports, 80 and 443. But the other services like DB and Redis are exposed on random ports. I propose that all services be exposed on well-known ports to enhance user-friendliness. And additionally add a build option for not exposing any ports that would best accommodate extensibility and customization of ports in an override file.

**Comment by keithbentrup** [comment]
The ports are already exposed. You would just map them to _your_ desired local ports. Ideally, we don't map them for everyone by default in the generated `docker-compose.yml` file because not everyone has the same use case. If fact, I think we should actually **move** some of the existing default port mappings from the generated `docker-compose.yml` because it's already limiting in a couple ways (1. hinders multiple stacks 2. interferes with existing local services) and doesn't account for how docker-compose yaml files inherit the `ports` key (cumulative, not overriding).

A simple, sample reusable docker-compose.override.yml placed in the dist/ dir and mapped in composer.json to /docker-compose.override.yml will accomplish the desired result. It also provides the added benefit of a clear point of further extension for end users.

```
# contents of proposed static file: docker-compose.override.yml 
# (OR docker-compose.override.yml.sample if desired. see comments below)

version: '2.1'
services:
  web:
    ports:
      - 80:80
  tls:
    ports:
      - 443:443
  db:
    ports:
      - 3306:3306
  redis:
    ports:
      - 6379:6379
```

I'm for further discussing what's the right "default". Should this be docker-compose.override.yml or docker-compose.override.yml.sample? Should the content only have the web and tls ports mapped, and have db & redis (and others) commented out ready for the user to uncomment if desired.

However, I really don't think default port mappings belong "locked" in php code that's much harder to for a casual user to extend/fork, undo, or customize to their desired use cases. The service names are not going to change nor are the standard port mappings, so this should be a simple static file that's intended _(but not necessarily required)_ to be modified by the end user with intelligent defaults that account for 1) how docker-compose inheritance works 2) the current most common use case 3) not limiting to a wider audience with a variety of uses.
