### ISSUE TITLE
Magento 2.4.2 Community Edition: creating admin user issue

### ISSUE THREAD

**Issue by tomaszmichalak** [magento/magento-cloud-docker#321]
I get an error when the administrator user is created with the CLI:
```
In Compat.php line 1946:                                                                                                               
  This is not implemented, as it is not possible to implement Argon2i with acceptable performance in pure-PHP  
```

### Preconditions

1.  Using docker-compose with `1.2.2` images with Magento `2.4.2` (community edition).
2. My configuration works correctly with Magento `2.4.1`, no errors.
3. I configured Composer `v2` (`COMPOSER_VERSION=2.0.12`).
4. When I run `docker-compose run cli magento-installer admin:user:create ...` I get the error.
5. I checked the `libsodium` library in FPM docker image:
    ```
    root@fpm:> /usr/local/bin/pecl install libsodium
    pecl/libsodium is already installed and is the same as the released version 2.0.23
    ```
6. The error also occurs during the installation:

    ```bash
    Updating to version 2.0.12 (stable channel).
       Downloading (100%)         
    Use composer self-update --rollback to return to version 1.10.16
    Creating Magento (2.4.2) project from composer
    Creating a "magento/project-community-edition=2.4.2" project at "./"
    Installing magento/project-community-edition (2.4.2)
      - Installing magento/project-community-edition (2.4.2): Extracting archive
    Created project in /app
    ...
      - Locking paragonie/sodium_compat (v1.16.0)
    ...
      - Installing paragonie/sodium_compat (v1.16.0): Extracting archive
    ...
    [Progress: 1308 / 1314]
    Enabling caches:
    Current status:
    layout: 1
    block_html: 1
    full_page: 1
    [Progress: 1309 / 1314]
    Installing admin user...

    In Compat.php line 1946:
                                                                                                               
      This is not implemented, as it is not possible to implement Argon2i with acceptable performance in pure-PHP  
    ```
7. I verified also my local docker images:
    ```bash
    magento/magento-cloud-docker-php                          7.4-fpm-1.2.2    9b4ab532facb   5 weeks ago     793MB
    magento/magento-cloud-docker-php                          7.4-cli-1.2.2    4c6dd6192823   5 weeks ago     1.03GB
    ```

### Steps to reproduce

1. Run: `docker-compose run cli magento-installer admin:user:create --admin-firstname=testadmin --admin-lastname=Integration --admin-email=me@example.com --admin-user=testadmin --admin-password=some-password`.
2. Install Magento 2.4.2 Community Edition with Composer 2, then run `setup:install` with some parameters:

```
$MAGENTO_COMMAND setup:install \
        --db-host=$M2SETUP_DB_HOST \
        --db-name=$M2SETUP_DB_NAME \
        --db-user=$M2SETUP_DB_USER \
        --db-password=$M2SETUP_DB_PASSWORD \
        --base-url=$M2SETUP_BASE_URL \
        --admin-firstname=$M2SETUP_ADMIN_FIRSTNAME \
        --admin-lastname=$M2SETUP_ADMIN_LASTNAME \
        --admin-email=$M2SETUP_ADMIN_EMAIL \
        --admin-user=$M2SETUP_ADMIN_USER \
        --admin-password=$M2SETUP_ADMIN_PASSWORD \
        --search-engine=elasticsearch7 \
        --elasticsearch-host=elasticsearch \
        --elasticsearch-port=9200 \
        --elasticsearch-enable-auth=false \
        --elasticsearch-index-prefix=magento2 \
        --elasticsearch-timeout=15
```

### Expected result
1. Admin user is created.

### Actual result
<img width="1130" alt="Screenshot 2021-05-23 at 11 47 30" src="https://user-images.githubusercontent.com/8047609/119255540-b2074a00-bbbc-11eb-86f5-3c971a8686c2.png">

**Comment by tomaszmichalak** [comment]
I found some advice here: https://community.magento.com/t5/Installing-Magento-2-x/Magento-2-4-2-Update-Admin-Error/m-p/468366#M9452 but it does not work as I have `libsodium` installed and enabled.

**Comment by tomaszmichalak** [comment]
I also checked `magento / magento-cloud-docker-php: 7.4-fpm-1.2.3`, but the `7.4-cli-1.2.3` tag is missing . This is the official release? Why is it not listed here: https://github.com/magento/magento-cloud-docker/releases? 

Could you please provide the file `docker-compose.yml` used during the verification of` 2.4.2`. It would be very useful to rule out some design-specific changes.

**Comment by shiftedreality** [comment]
@oshmyheliuk could you please check the tag's integrity?

**Comment by oshmyheliuk** [comment]
Hi @tomaszmichalak, thanks for noticing a missing tag. There was an issue with the build on the docker hub.

Also, `magento-cloud-docker` 1.2.3 is not released yet, please use the latest released version 1.2.2

**Comment by tomaszmichalak** [comment]
@oshmyheliuk Are you using the [Semantic Versioning](https://semver.org/) strategy? Do you create a new image tag every time you release some bug-fixes? I'm not sure, but I saw that 1.2.2 image changed some time ago - it is important that the tags once deployed do not change.

**Comment by oshmyheliuk** [comment]
@tomaszmichalak Images shouldn't be changed after the official release. 
After the release `magento-cloud-docker:1.2.2` we have removed all `*-1.2.2` builds, so there shouldn't be updates for such images, if you see some changes please let us know, we will investigate this issue.
I just checked the docker hub and didn't find any configured builds for `*-1.2.2` images.

**Comment by tomaszmichalak** [comment]
@oshmyheliuk Could you please provide the `docker-compose.yml` file which you are using to validate Magento` 2.4.2` setup?

**Comment by oshmyheliuk** [comment]
@tomaszmichalak we are using a file generated based on `magento-cloud` template. You can run the next commands and it will create a `docker-compose.yml` file for Magento 2.4.2
```
git clone --branch 2.4.2 git@github.com:magento/magento-cloud.git magento-cloud-2.4.2 && \
cd magento-cloud-2.4.2 && \
composer update && \
vendor/bin/ece-docker build:compose
```

**Comment by tomaszmichalak** [comment]
@oshmyheliuk Is it possible to generate the `docker-compose.yml` file without an active Magento Commerce Cloud user license ?

> [You must have an active Magento Commerce Cloud user license to use the example in this repository.](https://github.com/magento/magento-cloud/tree/2.4.2)

When I try to use my open-source auth data, I get an error:

```
./composer.phar update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires magento/magento-cloud-metapackage >=2.4.2 <2.4.3, found magento/magento-cloud-metapackage[2.4.2] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
```

**Comment by tomaszmichalak** [comment]
@oshmyheliuk When I create `db`/`elastic search` with docker using my `docker-compose.yml` and then run the `bin/magento setup:install` locally from my local filesystem (`PHP 7.4.19`), I can install Magento `2.4.2` without any problems:
```
[Progress: 1309 / 1314]
Installing admin user...
[Progress: 1310 / 1314]
Caches clearing:
Cache cleared successfully
[Progress: 1311 / 1314]
Disabling Maintenance Mode:
[Progress: 1312 / 1314]
Post installation file permissions check...
For security, remove write permissions from these directories: '/.../magento-generate/magent-create-project-2-4-2/project-community-edition/app/etc'
[Progress: 1313 / 1314]
Write installation date...
[Progress: 1314 / 1314]
[SUCCESS]: Magento installation complete.
[SUCCESS]: Magento Admin URI: /admin_7vu1pj
Nothing to import.
```
I think that there is some issue in the `magento/magento-cloud-docker-php:7.4-cli-1.2.2` image. Could you please verify the installation process? Maybe the image is corrupted?

**Comment by oshmyheliuk** [comment]
@tomaszmichalak so sorry, I totally forgot that `magento-cloud` requires a license.
I just tested the installation with the same PHP images as you have and didn't get any errors.
```
docker images | grep php                                                   
magento/magento-cloud-docker-php             7.4-fpm-1.2.2   9b4ab532facb   6 weeks ago    793MB
magento/magento-cloud-docker-php             7.4-cli-1.2.2   4c6dd6192823   6 weeks ago    1.03GB
```

Please check that `sodium` extension is set in `PHP_EXTENSIONS` variable:
```
...
environment:
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium'
```

My `docker-compose.yaml` generated for production mode from 2.4.2 template :
```
version: '2.1'
services:
  db:
    hostname: db.magento2.docker
    image: 'mariadb:10.3'
    shm_size: 2gb
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    ports:
      - '3306'
    volumes:
      - '.docker/mnt:/mnt:rw,delegated'
      - 'mymagento-magento-db:/var/lib/mysql'
    healthcheck:
      test: 'mysqladmin ping -h localhost -pmagento2'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - db.magento2.docker
  redis:
    hostname: redis.magento2.docker
    image: 'redis:5.0'
    volumes:
      - /data
    ports:
      - 6379
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - redis.magento2.docker
  elasticsearch:
    hostname: elasticsearch.magento2.docker
    image: 'magento/magento-cloud-docker-elasticsearch:7.7-1.2.2'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    networks:
      magento:
        aliases:
          - elasticsearch.magento2.docker
  fpm:
    hostname: fpm.magento2.docker
    image: 'magento/magento-cloud-docker-php:7.4-fpm-1.2.2'
    extends: generic
    volumes:
      - '.:/app:ro,delegated'
      - 'mymagento-vendor:/app/vendor:ro,delegated'
      - 'mymagento-generated:/app/generated:ro,delegated'
      - 'mymagento-var:/app/var:rw,delegated'
      - 'mymagento-app-etc:/app/app/etc:rw,delegated'
      - 'mymagento-pub-media:/app/pub/media:rw,delegated'
      - 'mymagento-pub-static:/app/pub/static:rw,delegated'
      - '.docker/mnt:/mnt:rw,delegated'
    networks:
      magento:
        aliases:
          - fpm.magento2.docker
    depends_on:
      db:
        condition: service_healthy
  web:
    hostname: web.magento2.docker
    image: 'magento/magento-cloud-docker-nginx:1.19-1.2.2'
    extends: generic
    volumes:
      - '.:/app:ro,delegated'
      - 'mymagento-vendor:/app/vendor:ro,delegated'
      - 'mymagento-generated:/app/generated:ro,delegated'
      - 'mymagento-var:/app/var:rw,delegated'
      - 'mymagento-app-etc:/app/app/etc:rw,delegated'
      - 'mymagento-pub-media:/app/pub/media:rw,delegated'
      - 'mymagento-pub-static:/app/pub/static:rw,delegated'
      - '.docker/mnt:/mnt:rw,delegated'
    environment:
      - WITH_XDEBUG=0
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
    networks:
      magento:
        aliases:
          - web.magento2.docker
    depends_on:
      fpm:
        condition: service_started
  varnish:
    hostname: varnish.magento2.docker
    image: 'magento/magento-cloud-docker-varnish:6.2-1.2.2'
    networks:
      magento:
        aliases:
          - varnish.magento2.docker
    depends_on:
      web:
        condition: service_started
  tls:
    hostname: tls.magento2.docker
    image: 'magento/magento-cloud-docker-nginx:1.19-1.2.2'
    extends: generic
    networks:
      magento:
        aliases:
          - magento2.docker
    environment:
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
      - UPSTREAM_HOST=varnish
      - UPSTREAM_PORT=80
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      varnish:
        condition: service_started
  generic:
    hostname: generic.magento2.docker
    image: 'magento/magento-cloud-docker-php:7.4-cli-1.2.2'
    env_file: ./.docker/config.env
    environment:
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium'
  build:
    hostname: build.magento2.docker
    image: 'magento/magento-cloud-docker-php:7.4-cli-1.2.2'
    extends: generic
    volumes:
      - '.:/app:rw,delegated'
      - 'mymagento-vendor:/app/vendor:rw,delegated'
      - 'mymagento-generated:/app/generated:rw,delegated'
      - '~/.composer/cache:/root/.composer/cache:rw,delegated'
    networks:
      magento-build:
        aliases:
          - build.magento2.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  deploy:
    hostname: deploy.magento2.docker
    image: 'magento/magento-cloud-docker-php:7.4-cli-1.2.2'
    extends: generic
    volumes:
      - '.:/app:ro,delegated'
      - 'mymagento-vendor:/app/vendor:ro,delegated'
      - 'mymagento-generated:/app/generated:ro,delegated'
      - 'mymagento-var:/app/var:rw,delegated'
      - 'mymagento-app-etc:/app/app/etc:rw,delegated'
      - 'mymagento-pub-media:/app/pub/media:rw,delegated'
      - 'mymagento-pub-static:/app/pub/static:rw,delegated'
      - '.docker/mnt:/mnt:rw,delegated'
    networks:
      magento:
        aliases:
          - deploy.magento2.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  mailhog:
    hostname: mailhog.magento2.docker
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      magento:
        aliases:
          - mailhog.magento2.docker
volumes:
  mymagento-vendor: {  }
  mymagento-generated: {  }
  mymagento-var: {  }
  mymagento-app-etc: {  }
  mymagento-pub-media: {  }
  mymagento-pub-static: {  }
  mymagento-magento-db: {  }
networks:
  magento:
    driver: bridge
  magento-build:
    driver: bridge
```
