### ISSUE TITLE
'Your requirements could not be resolved to an installable set of packages.'

### ISSUE THREAD

**Issue by dshevtsov** [magento/magento-cloud-docker#330]
### Preconditions

1. macOS 11.5
2. Docker version 20.10.7, build f0df350
3. Composer version 2.0.12
4. PHP 7.4.20

### Steps to reproduce

1. Clean / purge data on Docker
1. `git clone --branch 2.4.3 git@github.com:magento/magento-cloud.git magento-cloud-2.4.3`
1.  `cd magento-cloud-2.4.3`
1. `cp ~/.composer/auth.json . || exit`
1. `COMPOSER_MEMORY_LIMIT=-1 composer update`
1. `./vendor/bin/ece-docker build:compose`
1. `docker-compose up --detach`
1. `docker-compose run --rm build cloud-build`

### Expected result

1. No failures are expected

### Actual result

```
$ docker-compose run --rm build cloud-build
Creating magento-cloud-243_build_run ... done
Cleaning directories:
Cleaning setup directory.
Cleaning vendor directory.
Cleaning generated directory.
Removing app/etc/env.php file
Installing dependencies.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ocramius/proxy-manager 2.10.1 -> satisfiable by ocramius/proxy-manager[2.10.1].
    - ocramius/proxy-manager 2.10.1 requires composer-runtime-api ^2.0.0 -> no matching package found.
  Problem 2
    - ocramius/proxy-manager 2.10.1 requires composer-runtime-api ^2.0.0 -> no matching package found.
    - symfony/proxy-manager-bridge v4.4.18 requires ocramius/proxy-manager ~2.1 -> satisfiable by ocramius/proxy-manager[2.10.1].
    - Installation request for symfony/proxy-manager-bridge v4.4.18 -> satisfiable by symfony/proxy-manager-bridge[v4.4.18].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
ERROR: 2
```

**Comment by BaDos** [comment]
Hi @dshevtsov,
Please, try the one of these:
 - use 1st composer on the local machine
- update composer inside docker before running the build phase

**Comment by dshevtsov** [comment]
> update composer inside docker before running the build phase

How do I do this?

**Comment by andriyShevtsov** [comment]
Answered in slack

**Comment by dshevtsov** [comment]
Changing local Composer version helped.

Though it is expected to use Composer 2 since version 2.4.2 per [official system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html).

**Comment by YPyltiai** [comment]
@BaDos , any fixes required here? I think @dshevtsov is right saying that Composer 2 is recommended, so rolling back to v1.x is not an obvious solution.

**Comment by BaDos** [comment]
@dshevtsov @YPyltiai 
By default MCD use Composer 1
After generating docker-compose.yaml file you can add ENV variable with specific composer version:

For example:
```yaml
...
  generic:
    hostname: generic.magento2.docker
    image: 'magento/magento-cloud-docker-php:8.0-cli-1.3.0'
    env_file: ./.docker/config.env
    environment:
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium'
      - 'SENDMAIL_PATH=/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025'
      - 'COMPOSER_VERSION=2.1.9'
...
```
