### ISSUE TITLE
mailhog service not generated in docker-compose.yml

### ISSUE THREAD

**Issue by andreidragutu** [magento/magento-cloud-docker#339]
### Preconditions
1. Docker Desktop 4.3.2, Engine 20.10.11, Compose 1.29.2 on macOS Monterey Apple Silicon (M1) - but not limited to this environment
2. Magento Commerce 2.4.3-p1, php 7.4, MariaDB 10.4

### Steps to reproduce
1. **Run**: `$ ./vendor/bin/ece-docker build:compose --mode="developer" --sync-engine="mutagen" --with-cron --mailhog-smtp-port=1025 --mailhog-http-port=8025` **OR simply run**: `$ ./vendor/bin/ece-docker build:compose --mailhog-smtp-port=1025 --mailhog-http-port=8025`
2. Success message: Configuration was built.
3. mailhog service is missing in docker-compose.yml but the header of docker-compose.yml is: 
```
# ./vendor/bin/ece-docker 'build:compose' --mode=developer --sync-engine=mutagen --with-cron --mailhog-smtp-port=1025 --mailhog-http-port=8025
version: '2.1'
```

### Expected result

```
services:
  mailhog:
    hostname: mailhog.magento2.docker
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      magento:
        aliases:
          - mailhog.magento2.docker
```

### Actual result

mailhog service is missing from docker-compose.yml. We have to manually add it in docker-compose.override.yml.
