### ISSUE TITLE
[Cloud Docker Core] TLS Proxy Times Out after 15 Seconds

### ISSUE THREAD

**Issue by ejsexton82** [magento/magento-cloud-docker#35]
### Preconditions
1. Magento 2.3.1

### Steps to reproduce
1. Perform any action on HTTPS that takes longer than 15 seconds, such as deleting a customer.

Note: Only occurs on HTTPS pages that have not been cached by Varnish.

### Expected result
1. The website should perform the expected action.

### Actual result
1. The website displays the following error message:

> An internal server error occurred. Please try again later.

2. And `docker-compose logs tls` displays the following error:

```
tls_1            | (7f07bb9ca700) e500 for 172.18.0.1 response error read from 172.18.0.9:80/POST /admin/scommerce_gdpr/newsletter/deletePersonalData/key/8529da357b06edf6f740fa28ad64c857b1d95912ee97c27bbcb7962b6b5674cc/ HTTP/1.1: Connection timed out (14.967 secs)
```

### Fix
Add the `TimeOut 300` parameter to the pound.cfg file.

### Workaround
Add the `HTTPS_UPSTREAM_SERVER_PORT` to the `docker-compose.yml` file:
```yaml
  tls:
    image: 'magento/magento-cloud-docker-tls:latest'
    ports:
      - '443:443'
    external_links:
      - 'varnish:varnish'
    depends_on:
      - varnish
    environment:
      HTTPS_UPSTREAM_SERVER_PORT: "80\n\t\t\tTimeOut 300"
```
