### ISSUE TITLE
Missing following extensions: 'ftp'

### ISSUE THREAD

**Issue by jbruni** [magento/magento-cloud-docker#377]
### Summary of the issue

 `Missing following extensions: 'ftp'` error when running `docker-compose run --rm deploy cloud-deploy`

### Steps to reproduce

```sh
git clone https://github.com/magento/magento-cloud.git
cd magento-cloud
composer install
composer require magento/extension-b2b
./vendor/bin/ece-docker 'build:compose' --mode=developer --no-varnish --with-xdebug --set-docker-host --with-entrypoint
docker-compose up -d
# set a crypt key
pico app/etc/env.php
# replace "mysqladmin" by "mariadb-admin"
pico docker-compose.yml
docker-compose run --rm deploy cloud-deploy
```

### Expected result

Successful deployment

### Actual result

 `Missing following extensions: 'ftp'` error

![Image](https://github.com/user-attachments/assets/a37d314e-f50f-4e91-ba23-5bd3a5e07517)

**Comment by hostep** [comment]
It was [supposed to be fixed already](https://github.com/magento/magento-cloud-docker/pull/367#issuecomment-2579322420) I believe, but I haven't double checked myself since I don't use this docker image.

**Comment by patrickheinzelmann** [comment]
Hi,

Check your file  .docker-composer.yml for this:

```
 generic:
    hostname: generic.magento2.docker
    image: 'magento/magento-cloud-docker-php:8.4-cli-1.4.3'
    env_file: ./.docker/config.env
    environment:
      - MAGENTO_RUN_MODE=developer
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium'
      - 'SENDMAIL_PATH=/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025'
```

Add ftp at the end of the PHP_EXTENSIONS.

It seems the the generation for the docker compose is generating an uncomplete file. It also generating the test "mysqladmin ping -h localhost -pmagento2" instead "mariadb-admin ping -h localhost -pmagento2".
