### ISSUE TITLE
[Cloud Docker Core] Secure Connection Works With Warning Regarding Certificate

### ISSUE THREAD

**Issue by YPyltiai** [magento/magento-cloud-docker#45]
Internal ID: `MAGECLOUD-3534`

**Steps to reproduce:**
- Deploy Magento using Cloud Docker
- Open storefront using HTTPS

**Expected behavior:**
- Storefront opens with valid certificate

**Actual behavior:**
- Storefront opens with warning about not recognized self-signed certificate

**Comment by shiftedreality** [comment]
Internal task: https://jira.corp.magento.com/browse/MCLOUD-2579

**Comment by aepod** [comment]
mkcert could handle this requirement, a command would need to be run from the browser host, for each developer.
https://github.com/FiloSottile/mkcert

The choice for http://magento2.docker/ as a domain limits this quite a bit. 

Alternative requirements instead of trying to support the magento2.docker domain would be to  use an FQDN with a wildcard cert that can be included in the configuration easily.  So certs would be stored in ./docker/nginx/ssl for instance, and filenames and domain names would have to be established in the .magento.app.yaml or something along these lines.

Either way, this issue seems like it needs more definition. So that a solution actually solves the underlying problem, adding mkcert could work but it wouild require some manual steps.

**Comment by YPyltiai** [comment]
@shiftedreality is this one resolved or still the case?

**Comment by shiftedreality** [comment]
No, this is still open

**Comment by aepod** [comment]
Adding the following to nginx config allows for certbot to work:

```
    location /.well-known/acme-challenge/ {
        default_type text/plain;
        try_files $uri =404;
    }
```

Then I was able to run certbot in my local box, I had to have the FQ domain name DNS pointed to my IP.

Then generate the cert
```
certbot certonly --manual --preferred-challenges=http -d example.domain.com
```
It will require you to place the file in pub/.well-known/acme-challenge/ 

In this case, the certs were generated and placed, and all I had to do was mount them into containers. 

```
  web:
    volumes:
      - .certbot/config/live/example.domain.com/fullchain.pem:/etc/nginx/ssl/magento.crt
      - .certbot/config/live/example.domain.com/privkey.pem:/etc/nginx/ssl/magento.key
  tls:
    volumes:
      - .certbot/config/live/example.domain.com/fullchain.pem:/etc/nginx/ssl/magento.crt
      - .certbot/config/live/example.domain.com/privkey.pem:/etc/nginx/ssl/magento.key
```

Customized the routes in .docker/config.php and then regenerating the build:compose and everything worked as expected.
