### ISSUE TITLE
[Cloud Docker Core] Windows Deployment Bug

### ISSUE THREAD

**Issue by YPyltiai** [magento/magento-cloud-docker#57]
Latest versions of ECE-Tools build magento volumes with an environment variable:
```
magento:
    driver_opts:
      type: none
      device: '${PWD}'
      o: bind
```

`${PWD}` is not available on Windows machines and must be replaced by the full path to current directory.

**To Do:**
* Detect OS during docker-compose file generation and put the path to the current directory for Windows machines
